<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/response.php';

function map_match_row(array $r): array {
  return [
    "id" => (int)$r["id"],
    "date" => $r["match_date"],
    "stadium" => $r["stadium"],
    "homeTeam" => ["id"=>$r["home_team_id"], "name"=>$r["home_team_name"], "shortName"=>$r["home_team_short"]],
    "awayTeam" => ["id"=>$r["away_team_id"], "name"=>$r["away_team_name"], "shortName"=>$r["away_team_short"]],
    "homeScore" => (int)$r["home_score"],
    "awayScore" => (int)$r["away_score"],
    "stats" => [
      "possessionHome" => (int)$r["possession_home"],
      "possessionAway" => (int)$r["possession_away"],
      "shotsHome" => (int)$r["shots_home"],
      "shotsAway" => (int)$r["shots_away"],
      "shotsOnTargetHome" => (int)$r["sot_home"],
      "shotsOnTargetAway" => (int)$r["sot_away"],
      "cornersHome" => (int)$r["corners_home"],
      "cornersAway" => (int)$r["corners_away"],
    ],
  ];
}

function get_matches(): void {
  $pdo = db();
  $rows = $pdo->query("SELECT * FROM matches ORDER BY match_date DESC")->fetchAll();
  $data = array_map("map_match_row", $rows);
  json_response(["items" => $data]);
}

function get_match_detail(int $id): void {
  $pdo = db();
  $stmt = $pdo->prepare("SELECT * FROM matches WHERE id = ?");
  $stmt->execute([$id]);
  $row = $stmt->fetch();
  if (!$row) json_response(["error" => "NOT_FOUND"], 404);
  json_response(map_match_row($row));
}

function post_ai_analysis(): void {
  // MVP: 서버만 먼저. 나중에 OpenAI 붙이기.
  $body = json_decode(file_get_contents("php://input"), true) ?: [];
  $matchId = (int)($body["matchId"] ?? 0);

  if ($matchId <= 0) json_response(["error" => "BAD_REQUEST", "message" => "matchId required"], 400);

  $pdo = db();
  $stmt = $pdo->prepare("SELECT * FROM matches WHERE id = ?");
  $stmt->execute([$matchId]);
  $row = $stmt->fetch();
  if (!$row) json_response(["error" => "NOT_FOUND"], 404);

  $m = map_match_row($row);
  $text = "Result: {$m['homeTeam']['shortName']} {$m['homeScore']}-{$m['awayScore']} {$m['awayTeam']['shortName']}\n\n"
    . "Key points:\n"
    . "- Possession: {$m['stats']['possessionHome']}% - {$m['stats']['possessionAway']}%\n"
    . "- Shots on Target: {$m['stats']['shotsOnTargetHome']} - {$m['stats']['shotsOnTargetAway']}\n"
    . "- Corners: {$m['stats']['cornersHome']} - {$m['stats']['cornersAway']}\n\n"
    . "AI summary: (stub) This analysis will be generated by the AI server later.";

  json_response(["matchId" => $matchId, "text" => $text]);
}
